version: '3'
services:
  mentalHealthDockerDeployment:
    container_name: mentalHealthDockerDeployment
    image: mentalhealth_deployment
    volumes:
      - '$PWD/deployment_files:/workspace'
    ports:
      - '8000:8000'
      - '8001:8001'
    working_dir: /workspace
    tty: true
